
services:
  db:
    image: postgres:latest
    container_name: postgres-jpa-db
    environment:
      POSTGRES_DB: albert-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: